const crypto = require("crypto");
const { createClient } = require("@supabase/supabase-js");

module.exports = async (req, res) => {
  if (req.method !== "POST") {
      return res.status(405).json({ error: "Method not allowed" });
        }

          try {
              const {
                    razorpay_order_id,
                          razorpay_payment_id,
                                razorpay_signature,
                                      clientId,
                                            projectId,
                                                  amount,
                                                        currency,
                                                            } = req.body || {};

                                                                if (
                                                                      !razorpay_order_id ||
                                                                            !razorpay_payment_id ||
                                                                                  !razorpay_signature
                                                                                      ) {
                                                                                            return res.status(400).json({
                                                                                                    verified: false,
                                                                                                            error: "Missing payment verification data",
                                                                                                                  });
                                                                                                                      }

                                                                                                                          // Verify Razorpay signature
                                                                                                                              const expectedSignature = crypto
                                                                                                                                    .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
                                                                                                                                          .update(`${razorpay_order_id}|${razorpay_payment_id}`)
                                                                                                                                                .digest("hex");

                                                                                                                                                    const verified =
                                                                                                                                                          expectedSignature.length === razorpay_signature.length &&
                                                                                                                                                                crypto.timingSafeEqual(
                                                                                                                                                                        Buffer.from(expectedSignature),
                                                                                                                                                                                Buffer.from(razorpay_signature)
                                                                                                                                                                                      );

                                                                                                                                                                                          if (!verified) {
                                                                                                                                                                                                return res.status(400).json({
                                                                                                                                                                                                        verified: false,
                                                                                                                                                                                                                error: "Payment verification failed",
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                              // Connect to Supabase using the server-only service role key
                                                                                                                                                                                                                                  const supabaseUrl = process.env.SUPABASE_URL.replace(/\/rest\/v1\/?$/, "");

                                                                                                                                                                                                                                  const supabase = createClient(
                                                                                                                                                                                                                                    supabaseUrl,
                                                                                                                                                                                                                                      process.env.SUPABASE_SERVICE_ROLE_KEY
                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                      // Save payment in Supabase
                                                                                                                                                                                                                                                          const { error: dbError } = await supabase
                                                                                                                                                                                                                                                                .from("payments")
                                                                                                                                                                                                                                                                      .insert({
                                                                                                                                                                                                                                                                              client_id: clientId ? Number(clientId) : null,
                                                                                                                                                                                                                                                                                      project_id: projectId ? Number(projectId) : null,
                                                                                                                                                                                                                                                                                              razorpay_order_id,
                                                                                                                                                                                                                                                                                                      razorpay_payment_id,
                                                                                                                                                                                                                                                                                                              amount: Number(amount || 0),
                                                                                                                                                                                                                                                                                                                      currency: currency || "INR",
                                                                                                                                                                                                                                                                                                                              payment_type: "RAZORPAY",
                                                                                                                                                                                                                                                                                                                                      payment_status: "PAID",
                                                                                                                                                                                                                                                                                                                                              paid_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                        if (dbError) {
                                                                                                                                                                                                                                                                                                                                                              console.error("Supabase payment insert error:", dbError);

                                                                                                                                                                                                                                                                                                                                                                    return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                            verified: true,
                                                                                                                                                                                                                                                                                                                                                                                    saved: false,
                                                                                                                                                                                                                                                                                                                                                                                            error: "Payment verified but database save failed",
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                verified: true,
                                                                                                                                                                                                                                                                                                                                                                                                                      saved: true,
                                                                                                                                                                                                                                                                                                                                                                                                                            payment_id: razorpay_payment_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                  order_id: razorpay_order_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("Payment verification error:", error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                      verified: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            error: "Unable to verify payment",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };